name: Greetings

on:
  pull_request:
    types: [opened, synchronized]
  issues:
    types: [opened]

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: |
            # Welcome ${{ github.actor }} :tada:
            Congrats to your first issue!
          pr-message: |
            # Welcome ${{ github.actor }} :tada:
            Thanks for your first pull request! We'll review it soon.
